export const messageData = [
  {
    doctorName: 'Dr. Ajay Patel',
    appointmentTime: '13 January 2022, 09:40 AM',
    notificationTime: 'Today . 14:30',
    title: 'schedule changes',
    type: 'success',
    isRemainder: true,
    background: '#E5F4FF',
  },
  {
    doctorName: 'Dr. Ajay Patell',
    appointmentTime: '13 January 2022, 09:41 AM',
    notificationTime: 'Today . 14:31',
    title: 'Booking Success',
    type: 'success',
    background: '#E5F4FF',
  },
  {
    doctorName: 'Dr. Ajay Patelll',
    appointmentTime: '13 January 2022, 09:42 AM',
    notificationTime: 'Today . 14:32',
    title: 'Booking Rescheduled',
    type: 'resheduled',
    background: '#FFF5F2',
  },
  {
    doctorName: 'Dr. Ajay Pate',
    appointmentTime: '13 January 2022, 09:43 AM',
    notificationTime: 'Today . 14:33',
    title: 'Booking Canceled',
    type: 'cancelled',
    background: '#FFE0E4',
  },
];
