export const useLanguage = {
  NAME_REQUIRED: 'Name field is Required',
  BRANCH_REQUIRED: 'Branch is Required',
  THIS_FIELD_REQUIRED: 'This Field Required',
  INVALID_PASSWORD: 'Invalid password',
  FAILED: 'This Request Failed',
  EMAIL_REQUIRED: 'Email field is required',
  PHONE_REQUIRED: 'Phone Number is required',
  PASSWORD_REQUIRED: 'Password field is required',
  PASSWORD_INVALID: 'Password field is more than 8 characters',
  INVALID_EMAIL_ENTERED: 'Invalid email is entered',
  CONFIRM_PASSWORD: 'Password Does not Match',
  PASSWORD_LENGTH: 'Password should be greater than 8',
  CANCEL: 'Cancel',
  CONFIRM: 'Confirm',
  SAVE: 'SAVE',
  AGE_REQUIRED: 'Age field is Required',
  GENDER_REQUIRED: 'Gender field is Required',

};
